### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by lwlsw** [asterixgaul/digitalbattery13lite#1]
Where is the source code?

**Comment by asterixgaul** [comment]
Currently private

**Comment by lwlsw** [comment]
can you open source? i can learn it. 😁😁😁😁

**Comment by asterixgaul** [comment]
I may open source the iOS 11/12 DigitalNotchedBattery very soon (waiting to finish Lite version which is close).

I will not open source either of the DigitalBattery13 builds anytime soon, if ever

On 6 Jun 2020, at 10:55 am, 我是谁 <notifications@github.com> wrote:

﻿

can you open source? i can learn it. 😁😁😁😁

**Comment by asterixgaul** [comment]
I may open source the iOS 11/12 DigitalNotchedBattery very soon (waiting to finish Lite version which is close).

I will not open source either of the DigitalBattery13 builds anytime soon, if ever
